### ISSUE TITLE
Bower

### ISSUE THREAD

**Issue by epotvin** [urish/angular2-moment#1]
Hi,

this seems nice! Is it possible to put it on bower?

Emmanuel

**Comment by urish** [comment]
Thanks!

Are you using Angular2 with bower?

**Comment by epotvin** [comment]
I'm using it with Meteor from the https://github.com/netanelgilad/meteor-angular2 module, but I use the bower plugin to add client libraries to my project. 

Emmanuel

**Comment by urish** [comment]
@epotvin thanks for the input! Just published to bower, `angular2-moment`.

How did you discover this module?

**Comment by epotvin** [comment]
I searched angular2 and moment on google... You hit pretty high! Thanks for the quick response! I'll try it tonight and give you some feedback. 

Emmanuel

**Comment by urish** [comment]
thanks!
