### ISSUE TITLE
angular2 moment locale problem

### ISSUE THREAD

**Issue by codeggercom** [urish/angular2-moment#100]
I have locale function problem. Nothing does not change. Everthings is working but 'locale function' is not defined.

**app.module.ts**
import {MomentModule} from 'angular2-moment';
import * as moment from 'moment';
import 'moment/min/locales';

constructor(){
moment.locale('tr');
}

**Comment by urish** [comment]
Is `moment` defined? depending on your setup, you may need to import it like:

    import moment from 'moment';

**Comment by codeggercom** [comment]
Moment is defined. Timeago has been working. But Locale function is not defined.

**Comment by urish** [comment]
can you please include the following details about your environment?


* Angular version? 
* TypeScript version?
* `moment` version?
* Are you using the angular-cli? 
* Using Rollup/Webpack/System.js/Ionic/similar? 

thx

**Comment by codeggercom** [comment]
- ionic-angular: 2.0.0-rc.0
- typescript : 2.0.3
- angular2-moment: 1.0.0-beta.5
- not using angular-cli
- Ionic 2

thanks

**Comment by urish** [comment]
And which moment version?

**Comment by codeggercom** [comment]
Sorry , moment version : 2.15.1

**Comment by VeniOliver** [comment]
In ionic use:

`import moment from 'moment';
import 'moment/src/locale/tr';

moment.locale('tr);`

**Comment by codeggercom** [comment]
@VeniOliver Thank you! It's working now.
