### ISSUE TITLE
Ionic2 Error: Unexpected value 'MomentModule' imported by the module 'AppModule'

### ISSUE THREAD

**Issue by datpt154** [urish/angular2-moment#102]
**Description of the Issue and Steps to Reproduce:**

Hi teams,

here the way i applied angular2-moment to my application and I got the above error when i tried to run "ionic build". does anyone has any idea to workaround?

import { MomentModule  } from 'angular2-moment/module'; 
(or import { MomentModule  } from 'angular2-moment')

imports: [
    MomentModule,
    IonicModule.forRoot(MyApp)
  ],

Currently I'm using:
ionic2: 2.1.0
angular: 2.0.0
angular-moment: 1.0.0.beta.5

**Comment by Gp2mv3** [comment]
Hi,
I have the exact same issue...

Any help ?

**Comment by datpt154** [comment]
I solved my problem by replacing angular-moment to 1.0.0.beta4 version

**Comment by datencia** [comment]
I'm using the version 1.0.0-beta6 and works fine

**Comment by d3viant0ne** [comment]
Same issue in the latest RC on angular 2.1.2

**Comment by welksonramos** [comment]
@datpt154 I was having the same problem with version 1.0.0, i solved it this way:

import { MomentModule} from 'angular2-moment';

@NgModule({
  declarations: [
MyApp
...
],
  imports: [
     IonicModule.forRoot(MyApp),
     MomentModule
  ],
