### ISSUE TITLE
Module 'moment' has no exported member 'UnitOfTime'

### ISSUE THREAD

**Issue by maxmumford** [urish/angular2-moment#103]
**Description of the Issue and Steps to Reproduce:**

I'm getting the error `ERROR in [default] /Users/max/project/node_modules/angular2-moment/difference.pipe.d.ts:4:91` when compiling my project.

Duplicate exists #91 but installing typescript definitions from typings, and from @types/moment did not fix the issue.

**Please describe the issue and steps to reproduce, preferably with a code sample / plunker:**

I've installed the pikaday datepicker that relies on the moment typescript definition file to export several classes, one of which is UnitOfTime. 

As far as I can tell, my problem comes from the fact that the typescript definition file for moment included in angular2-moment doesn't export UnitOfTime. 

**Environment:**

* Angular version? 

2.0.0-beta.5

* TypeScript version?

2.0.0

* `moment` version?

"moment": "^2.15.0",

* Are you using `moment-timezone`? 

no

* Are you using the angular-cli? 

np

* Using Rollup/Webpack/System.js/Ionic/similar? 

webpack

**Comment by urish** [comment]
Hi, the TypeScript definition file for moment is not included in `angular2-moment`. It is a part of `moment` itself, since 2.13.0. If you installed another definition file, there could be a conflict, try removing it.

**Comment by maxmumford** [comment]
Ah I think you're right. This is more a pikaday issue than angular2-moment. Thanks

**Comment by dinoantonello** [comment]
I have the same problem, Can you explain in more detail how you fixed this issue?

**Comment by maxmumford** [comment]
Not fixed yet unfortunately! 

https://github.com/dbushell/Pikaday/issues/593

**Comment by artdias90** [comment]
+1

**Comment by kfurmann** [comment]
You guys can force
    "moment": "2.15.2",
in your package.json

**Comment by maxmumford** [comment]
Could you leave "+1" comments on this thread instead:

https://github.com/dbushell/Pikaday/issues/593

**Comment by artdias90** [comment]
thanks @kfurmann it works for me.

**Comment by maxmumford** [comment]
@kfurmann that didn't solve it for me. Changed package.json to look like:

    "moment": "2.15.2",

uninstalled moment and reinstalled with npm uninstall moment; npm install, but still getting the same warning.

**Comment by kfurmann** [comment]
Maybe remove whole node_modules folder and npm install. Btw, I'm running npm 3.10.9.

Also, for my project it wasn't about a warning, it broke the whole build (angular-cli/webpack).

**Comment by Cogitaria** [comment]
Inexplicably started getting this error after wiping out node_modules and clearing the npm cache with _npm cache clear_. _**Module 'moment' has no exported member 'UnitOfTime'**_

Had to disable type checking in tsconfig.json with **"skipLibCheck": false**

**Comment by urish** [comment]
Please see #112

**Comment by davidwill** [comment]
@maxmumford run 'rm -rf node_modules/moment && npm cache clean && npm install' after setting "moment": "2.15.2" in your package.json

**Comment by chadbr** [comment]
there is a new definition - moment.unitOfTime.*

**Comment by adambuczynski** [comment]
Reverting moment to 2.15.2 worked for us.

@chadbr If the definition changes and UnitOfTime is no longer valid, then that should be a major version bump as it's a breaking change..

**Comment by chadbr** [comment]
I agree - just passing on what got it working for me...
