### ISSUE TITLE
Show number of minutes after the hour

### ISSUE THREAD

**Issue by theunreal** [urish/angular2-moment#106]
**Description of the Issue and Steps to Reproduce:**

Did you search for duplicate issue? [**Yes** / No]

Please describe the issue and steps to reproduce, preferably with a code sample / plunker:

No issue just undocumented question.

I'm using the amTimeAgo Pipe. it's lovely, but in my case I need to get the format with the number of minutes after the hours. For example:

1 Hour and 42 minutes.
2 Hours and 13 minutes.
3 Hours and 15 minutes

In my app I have alot of 1-5 hours timings, so I need to show specific minutes after the hours.
Is it possible to achieve such output with the moment package and angular2-moment?

*Ensure your issue is isolated to angular2-moment. Issues involving third party tools will be closed unless submitted by the tool's author/maintainer.*

**Environment:**

Please answer the following questions:

* Angular version?  2.1
* TypeScript version? 2.0
* `moment` version? 1.0.0-beta.6
* Are you using `moment-timezone`? No
* Are you using the angular-cli?  Yes
* Using Rollup/Webpack/System.js/Ionic/similar? Webpack(angular cli)

**Comment by urish** [comment]
Hi, this use case is not covered by the library.

**Comment by theunreal** [comment]
Hey @urish , this is covered by the library at:

http://momentjs.com/docs/#/displaying/
http://momentjs.com/docs/#/durations/

**Comment by urish** [comment]
I meant to say this is not covered by the `angular2-moment` library. There is a pipe for `amDuration`, but it won't update automatically like `amTimeAgo` does

**Comment by theunreal** [comment]
Then it's impossible to know the exact time and hour when using `angular2-moment`? Wouldn't it be nice to work on different use cases the `moment` library covers?
