### ISSUE TITLE
 i had bug in angular2-moment

### ISSUE THREAD

**Issue by Ngocphu123** [urish/angular2-moment#11]
i used ionic 2 and angular2 for build app.

im run npm install --save angular2-moment
and i add  import {TimeAgoPipe} from 'angular2-moment'; 
pipes: [TimeAgoPipe],
for file .js
but it error 
Module parse failed: D:\xampp\htdocs\1000ngayvang_app\node_modules\angular2-mome
nt\TimeAgoPipe.ts Line 3: Unexpected token
You may need an appropriate loader to handle this file type.

**Comment by urish** [comment]
Can you try to change the import to

`
import {TimeAgoPipe} from 'angular2-moment/TimeAgoPipe.js';
`

and see if it helps?

**Comment by Ngocphu123** [comment]
thanks you so much


2016-02-02 5:18 GMT+07:00 Uri Shaked <notifications@github.com>:

> Can you try to change the import to
>
>
> import {TimeAgoPipe} from 'angular2-moment/TimeAgoPipe.js';
>
> and see if it helps?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/urish/angular2-moment/issues/11#issuecomment-178225478>
> .
>



-- 
                             Bùi Ngọc Phú

                             Mail:strongover@gmail.com

                             Phone: 0901 443 593

**Comment by danielgolub** [comment]
Hi,

I have the same bug. (even when I use @urish solution)

**Comment by urish** [comment]
@danielgolub are you using typescript?
have you got the latest release of angular2-moment (that is version 0.3.0)

**Comment by danielgolub** [comment]
@urish Yes.
I just installed it few minutes ago.

**Comment by urish** [comment]
Can you please include the output that you get?

**Comment by danielgolub** [comment]
When using the import code from the README file:
![image](https://cloud.githubusercontent.com/assets/1869601/12867892/6ea81e32-cd02-11e5-8f08-390e3ddb91c9.png)

When using the solution your wrote in this chat earlier:
![image](https://cloud.githubusercontent.com/assets/1869601/12867885/4956ccfa-cd02-11e5-8271-1b7af80e6616.png)

**Comment by urish** [comment]
seems to be a configuration problem. When you go to http://localhost:3000/angular2-moment, do you see the code of the module or a 404 error page?

**Comment by danielgolub** [comment]
404 error page.

**Comment by urish** [comment]
I would suggest to check your configuration, if you are using system.js you need to configure the module loader correctly so that it can correctly locate the `angular2-moment` package inside your node_modules directory.

**Comment by danielgolub** [comment]
Well I followed the "Hero" setup on angular.io website.
Here are the different configuration files I have:

tsconfig.json:
```
{
  "compilerOptions": {
    "target": "ES5",
    "module": "system",
    "moduleResolution": "node",
    "sourceMap": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "removeComments": false,
    "noImplicitAny": false
  },
  "exclude": [
    "node_modules"
  ]
}
```

package.json:
```
{
  "name": "SHIELDoX",
  "version": "1.0.0",
  "scripts": {
    "tsc": "tsc",
    "tsc:w": "tsc -w",
    "lite": "lite-server",
    "start": "concurrent \"npm run tsc:w\" \"npm run lite\" "
  },
  "license": "ISC",
  "dependencies": {
    "angular2": "2.0.0-beta.0",
    "angular2-moment": "^0.3.0",
    "es6-promise": "^3.0.2",
    "es6-shim": "^0.33.3",
    "reflect-metadata": "0.1.2",
    "rxjs": "5.0.0-beta.0",
    "systemjs": "0.19.6",
    "zone.js": "0.5.10"
  },
  "devDependencies": {
    "concurrently": "^1.0.0",
    "lite-server": "^1.3.1",
    "typescript": "^1.7.3"
  }
}
```

And on index.html:
```
		<!-- 2. Configure SystemJS -->
		<script>
		  System.config({
			packages: {
			  app: {
				format: 'register',
				defaultExtension: 'js'
			  }
			}
		  });
		  System.import('app/boot')
				.then(null, console.error.bind(console));
		</script>

```

**Comment by urish** [comment]
Can you please upload the entire code to a git repo?

**Comment by danielgolub** [comment]
@urish, I added you as a collaborator on the git repo.

**Comment by urish** [comment]
Seems like the following System.js configuration should do the trick for you:

	System.config({
		packageConfigPaths: ['node_modules/*/package.json'],
		paths: {
			'moment': '/node_modules/moment',
			'angular2-moment/*': '/node_modules/angular2-moment/*',
		},
		packages: {
			app: {
				format: 'register',
				defaultExtension: 'js'
			}
		},
		meta: {
			moment: {
				format: 'global',
				globals: {
					moment: 'moment'
				}
			}
		}
	});

And then, import the module as follows:

    import {TimeAgoPipe} from 'angular2-moment/TimeAgoPipe.js'; 

In general, I would suggest to study System.js in detail if you intend to use it in your project, it will save you much time in the future.

**Comment by danielgolub** [comment]
It works.
Anyway, I will read some more articles about System.js. It seems I was too enthusiastic about Angular2 that I ran too fast :P

Thanks.
