### ISSUE TITLE
Ionic 2: Module 'moment' has no exported member 'UnitOfTime'.

### ISSUE THREAD

**Issue by mauricionarcizo** [urish/angular2-moment#112]
I updated the ionic-app-scripts to 0.0.42 and on process 'transpile', I got the following error:

[14:21:19]  transpile started ...
[14:21:23]  typescript: ...nfo/app/node_modules/angular2-moment/difference.pipe.d.ts, line: 4
            Module 'moment' has no exported member 'UnitOfTime'.

       L3:  export declare class DifferencePipe implements PipeTransform {
       L4:   | moment.Moment, otherValue: Date | moment.Moment, unit?: moment.UnitOfTime, precision?: boolean): number;

[14:21:23]  transpile failed

As we can see, the 'UnitOfTime' is not an exported module from 'moment'. What I can do to solve this?

Angular2-moment version used is 1.0.0-beta.6.

**Comment by JasonGoemaat** [comment]
Same issue here.   I don't see anywhere in the momentjs documentation where 'UnitOfTime' exists.

**Comment by amarisi** [comment]
As a workaround until it gets fixed, I added `class UnitOfTime {}` inside of `declare namespace moment {}` in the file moment.d.ts. With this, the project at least compiles.

**Comment by urish** [comment]
I confirm that angular2-moment currently produces this error with moment 2.16.0. This is the specific commit that introduced that change: https://github.com/moment/moment/commit/8c0c6a33a1b81ab0c4b5b9567b5678c59af8accb

I hope to publish a new release that will address it within the next few days

**Comment by mauricionarcizo** [comment]
Work!
@urish thanks!

**Comment by bitterloa** [comment]
Just wanted to let others know what solution worked for me--I did not revert to the older version of moment -- I am using 2.17.1. Also I didn't need to change any typings files at all.

What I did, in my angular component .ts file was to cast my string variable into the moment

_some.component.ts_
```
let convertedChartPeriod: moment.unitOfTime.StartOf = <moment.unitOfTime.StartOf>this.chartPeriod;

var reportStartDate = moment(itemDate).startOf(convertedChartPeriod);
```

Things of Note:

- proper class name for v2.17.1 is `moment.unitOfTime.StartOf`
- use the `<moment.unitOfTime.StartOf>` with the "<>" brackets to cast the string into the proper class.
- No need to change any Damn typings files!

**Comment by jchavarria1983** [comment]
Hi everybody I have  this issue: 'moment' has no exported member 'DurationInputArg1'.
Someone knows what happen ?  @bitterloa @urish 

Complete error:
ERROR in C:/wamp64/www/ng2-admin/node_modules/ap-angular2-fullcalendar/node_modules/@types/fullcalendar/index.d.ts (154,27): Namespace 'moment' has no exported member 'DurationInputArg1'.

**Comment by InstanceOfMichael** [comment]
This is still happening for me.
```
ERROR in /home/ubuntu/app/node_modules/angular2-moment/subtract.pipe.d.ts
(4,42): error TS2694: Namespace 'moment' has no exported member 'DurationInputArg1'.

ERROR in /home/ubuntu/app/node_modules/angular2-moment/subtract.pipe.d.ts
(4,75): error TS2694: Namespace 'moment' has no exported member 'DurationInputArg2'.

ERROR in /home/ubuntu/app/node_modules/angular2-moment/difference.pipe.d.ts
(4,92): error TS2694: Namespace 'moment' has no exported member 'unitOfTime'.

ERROR in /home/ubuntu/app/node_modules/angular2-moment/add.pipe.d.ts
(4,42): error TS2694: Namespace 'moment' has no exported member 'DurationInputArg1'.

ERROR in /home/ubuntu/app/node_modules/angular2-moment/add.pipe.d.ts
(4,75): error TS2694: Namespace 'moment' has no exported member 'DurationInputArg2'.
```
`angular2-moment@1.7`
`moment@2.19.2`
