### ISSUE TITLE
Not working in IE11

### ISSUE THREAD

**Issue by pranz123** [urish/angular2-moment#119]
**Description of the Issue and Steps to Reproduce:**

I am using angular2-moment to parse date/time into the locale time. This functionality is working fine in Chrome but it is showing "invalid date" in IE.

Any help would be appreciated.

Did you search for duplicate issue? Yes

*Ensure your issue is isolated to angular2-moment. Issues involving third party tools will be closed unless submitted by the tool's author/maintainer.*

**Environment:**
Please answer the following questions:
* Angular version: 2.2.1
* TypeScript version: 2.0.1
* `moment` version: 1.0.0
* Are you using `moment-timezone`? No
* Are you using the angular-cli? Yes
* Using Rollup/Webpack/System.js/Ionic/similar? Webpack

**Comment by urish** [comment]
Hi, as far as I know, parsing dates by moment without using one of the predefined formats or specifying a custom format is deprecated, as the behavior is browser dependent (just like you are experiencing). Please see moment/moment#1407 for discussion and possible solutions.

**Comment by ndamnjanovic** [comment]
Hi, 

Is there a way to pass custom format to amTimeAgo pipe? Or is there another way I should fix this?

I have a string in format 'DD-MM-YYYY', and I keep getting Invalid date.

Thanks!
