### ISSUE TITLE
Excluding locales from bundle (webpacked)

### ISSUE THREAD

**Issue by junglebarry** [urish/angular2-moment#127]
**Description of the Issue and Steps to Reproduce:**

Did you search for duplicate issue? Yes - I found lots about locales, but they were about *setting* locale, not restricting imports.

Please describe the issue and steps to reproduce, preferably with a code sample / plunker:

I've added the package as an npm dependency (`"angular2-moment": "1.1.0"`), but have no explicit dependency on `moment` itself.  Everything is working as expected.

I'm using the pipes in a couple of places, and have imported the module into my project:

```typescript
import { MomentModule } from 'angular2-moment';
```

This is all as expected.  However, when I bundle my app using webpack, the full moment is included in the bundle, *including all its locales*.  This amounts to ~200KB.

I traced this back to the way angular2-moment is importing `moment`.

There seem to be a number of ways that one can import only the required locales from moment directly, but I'm not sure these will play nicely with angular2-moment.

So my question is: how can I configure angular2-moment such that, when it imports moment, it imports only the locales I want?

*Ensure your issue is isolated to angular2-moment. Issues involving third party tools will be closed unless submitted by the tool's author/maintainer.*

**Environment:**

Please answer the following questions:

* Angular version? 2.4.4 (but same effect on various versions up to 4RC1)
* TypeScript version? 2.0.10 - but same on 2.1
* `moment` version?  Not explicitly required; angular2-moment imports it for me.
* Are you using `moment-timezone`?   No
* Are you using the angular-cli?   Yes.
* Using Rollup/Webpack/System.js/Ionic/similar?   Yes (through angular/cli)

**Comment by urish** [comment]
Hi, 

I add the following line to my `plugins` section of the webpack configuration to avoid auto-importing all the moment.js locales and bloating my bundle:

    plugins: [
        ...
        // don't auto include all moment.js locales
        new webpack.ContextReplacementPlugin(/moment[\/\\]locale$/, /a^/),
    ]

Works like a charm.  If you google "webpack.ContextReplacementPlugin moment js" you will find more information about this, such as [this StackOverflow answer](http://stackoverflow.com/a/25426019/830623).

**Comment by junglebarry** [comment]
Thanks @urish.

It won't work for me, as I (like many, I suspect) am using webpack behind [angular CLI](https://github.com/angular/angular-cli).  The CLI does not provide access to the webpack configuration (without ejecting, which I don't want to do).

However, since the presence of the CLI is barely indicated in my original question, I consider this answered.

**Comment by urish** [comment]
I also found a relevant issue for the angluar-cli: https://github.com/angular/angular-cli/issues/5166

As a workaround, you can use [eject](https://github.com/angular/angular-cli/wiki/eject) and take over the control of the webpack configuration.
