### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by aslubsky** [urish/angular2-moment#13]
san@san-work:~$ cd /tmp
san@san-work:/tmp$ npm install angular2-moment
-
> angular2-moment@0.4.0 postinstall /tmp/node_modules/angular2-moment
> typings install

typings ERR! message Unable to resolve Typings dependencies
typings ERR! caused by Unable to find "typings.json" from "/tmp/node_modules/angular2-moment"

typings ERR! cwd /tmp/node_modules/angular2-moment
typings ERR! system Linux 3.16.0-60-generic
typings ERR! command "/usr/bin/nodejs" "/usr/lib/node_modules/typings/dist/bin/typings-install.js"
typings ERR! node -v v0.12.10
typings ERR! typings -v 0.6.8

typings ERR! If you need help, you may report this error at:
typings ERR!   <https://github.com/typings/typings/issues>

npm ERR! Linux 3.16.0-60-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "angular2-moment"
npm ERR! node v0.12.10
npm ERR! npm  v2.14.9
npm ERR! code ELIFECYCLE

npm ERR! angular2-moment@0.4.0 postinstall: `typings install`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the angular2-moment@0.4.0 postinstall script 'typings install'.
npm ERR! This is most likely a problem with the angular2-moment package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     typings install
npm ERR! You can get their info via:
npm ERR!     npm owner ls angular2-moment
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /tmp/npm-debug.log
san@san-work:/tmp$ 

------
/tmp/npm-debug.log here https://drive.google.com/file/d/0B5sf8URbEXr8NTQxRVk4X1hremc/view?usp=sharing

**Comment by urish** [comment]
Thanks for reporting, looking into this. In the meanwhile, you can use version 0.3.0.

**Comment by urish** [comment]
Fix released in 0.4.1

**Comment by aslubsky** [comment]
thanks
