### ISSUE TITLE
amCalendar causes protractor to timeout on waiting async Angular

### ISSUE THREAD

**Issue by romanovma** [urish/angular2-moment#132]
**Description of the Issue and Steps to Reproduce:**

Did you search for duplicate issue? [Yes]

Please describe the issue and steps to reproduce, preferably with a code sample / plunker:

e2e protractor tests fail after amCalendar pipe is used:

```Timed out waiting for asynchronous Angular tasks to finish after 50 seconds.```

*Ensure your issue is isolated to angular2-moment. Issues involving third party tools will be closed unless submitted by the tool's author/maintainer.*

**Environment:**

Please answer the following questions:

* Angular version: 4.0.0-rc.2
* TypeScript version: 2.2.1
* `moment` version: 1.1.0
* Are you using `moment-timezone`: no 
* Are you using the angular-cli: yes
* Using Rollup/Webpack/System.js/Ionic/similar?

**Comment by urish** [comment]
Hi, thank you for reporting this. Can you please check if wrapping the `setTimeout` in `initTimer()` with `runOutsideAngular` fixes this issue and send a PR?

https://github.com/urish/angular2-moment/blob/c20b846934f440db3d56b9c9f644e46957750951/src/calendar.pipe.ts#L73

**Comment by romanovma** [comment]
Yes, it helps :)
Unfortunately I don't know how to pass `ngZone` to the static method(which `initTimer` is) so I converted it to non-static and removed `refs` as we don't need then anymore in this case. That can cause performance issues but I don't have good environment to test near at hand. May you have some?
Please review and let me know if it is OK to leave `initTimer` as non-static or may be you know a good way how to pass `ngZone` to static methods. Thanks for helping.

**Comment by urish** [comment]
Awesome, thanks for the PR!

As for passing the `ngZone` instance to the `initTimer()`, I think the best way would just be to add it as a parameter - it is called by the [CalendarPipe](https://github.com/urish/angular2-moment/blob/c20b846934f440db3d56b9c9f644e46957750951/src/calendar.pipe.ts#L26) constructor, and you can pass the ngZone you have there. Does this make sense?

**Comment by romanovma** [comment]
Great idea! I have updated PR passing `ngZone` and `ChangeDetectorRef` as parameters. 

Not sure if we really need `ngZone.run(() => cdRef.markForCheck());` inside `setTimeout` so would be nice if you could review and let me know if the code is good or can be improved further.

**Comment by urish** [comment]
True, we don't need it - I left you a comment. We can entirely skip the `ChangeDetectorRef` parameter to `initTimer`, also, we can remove the `runOutsideAngular` call from the constructor (but keep that part that's inside - the subscribe call)
