### ISSUE TITLE
The pipe 'amAdd' coul not be found

### ISSUE THREAD

**Issue by datencia** [urish/angular2-moment#133]
**Description of the Issue and Steps to Reproduce:**

Did you search for duplicate issue? [Yes / No]
Yes

Please describe the issue and steps to reproduce, preferably with a code sample / plunker:

I'm trying to use the `amAdd` and `amSubtract` pipes with no luck. I'm getting this error on console:

![image](https://cloud.githubusercontent.com/assets/18591213/24052400/a220b96e-0b35-11e7-8fd6-037420d2fb27.png)

I have seen that these pipes are not declared & exported on the module. I'll send a PR to fix this.

**Environment:**

Please answer the following questions:

* Angular version? 2.4.8
* TypeScript version? 2.0.9
* `moment` version? 2.17.1
* Are you using `moment-timezone`? no
* Are you using the angular-cli? no
* Using Rollup/Webpack/System.js/Ionic/similar? Ionic

**Comment by urish** [comment]
Thanks! Will be released later today

**Comment by useitsoftware** [comment]
This still happens on 1.3.3, please fix it.

**Comment by datencia** [comment]
Hi all, I don't know if this is the right way to deal with it (I mean, answer over a closed issue).

I've created an empty project (using angular-cli) with a fresh installation of angular2-moment (v1.3.3) and everything is working as expected.
