### ISSUE TITLE
Expression X has changed after it was checked. Previous value...

### ISSUE THREAD

**Issue by lordgreg** [urish/angular2-moment#14]
Hi. As in readme, I've installed angular2-moment. It works perfect. The problem I'm having is, that I'm using the pipe in `@Component`:

```
<ion-card class="single-tweet">

  <ion-item>
    <ion-avatar item-left>
      <img src="{{tweet.user.profile_image_url_https}}">
    </ion-avatar>
    <ion-note item-right class="time">
      {{tweet.unixtime | amTimeAgo}}
    </ion-note>
    <div class="name">{{tweet.user.name}}</div>
    <small class="screen-name">@{{tweet.user.screen_name}}</small>
  </ion-item>

</ion-card>
```

I use this component on ListAll page. When clicking single ion-card, I'm jumping to details page, where I'm again using component above. If, in the meantime I update my tweet variable, I'll then get this error:

```
browser_adapter.js:76 EXCEPTION: Expression '
      {{tweet.unixtime | amTimeAgo}}
     in SingleTweet@7:38' has changed after it was checked. Previous value: '39 minutes ago'. Current value: '40 minutes ago' in [
      {{tweet.unixtime | amTimeAgo}}
     in SingleTweet@7:38]
```

and then:
```
TypeError: Cannot read property 'removeEventListener' of undefined
    at Content.ngOnDestroy (content.js:79)
    at AbstractChangeDetector.ChangeDetector_DetailPage_0.dehydrateDirectives (viewFactory_DetailPage:81)
    at AbstractChangeDetector.dehydrate (abstract_change_detector.js:141)
    at AbstractChangeDetector.destroyRecursive (abstract_change_detector.js:158)
    at AbstractChangeDetector.destroyRecursive (abstract_change_detector.js:165)
    at AppView.destroy (view.js:111)
    at AppViewManager_.destroyViewInContainer (view_manager.js:124)
    at ViewContainerRef_.remove (view_container_ref.js:116)
    at Array.<anonymous> (nav-controller.js:1108)
    at ViewController.destroy (view-controller.js:420)
```

Should I in between somehow disable timeago when I do the update? Any help would be perfect :+1:

**Comment by urish** [comment]
Hi, 

Can you please share a small plunkr example (or git repo) that reproduces the problem?

Thanks!

**Comment by lordgreg** [comment]
@urish 
I can give you my private bitbucket repo access. Please give me your email from that page and I'll give you more info there. If you're using slack or similar, please let me know.

**Comment by lordgreg** [comment]
@urish 

to add to my error, checking console, I see typescript has thrown few errors:

```
ERROR in [default] C:/test/node_modules/angular2-moment/CalendarPipe.ts:4:24
Cannot find module 'moment'.

ERROR in [default] C:/test//node_modules/angular2-moment/DateFormatPipe.ts:4:24
Cannot find module 'moment'.

ERROR in [default] C:/test//node_modules/angular2-moment/TimeAgoPipe.ts:4:24
Cannot find module 'moment'.
```

**Comment by urish** [comment]
@lordgreg are you using `typings` in your project?

try `typings install --save moment`

**Comment by lordgreg** [comment]
That fixed the errors in console. I'll try to make plunkr (no idea how since this is ionic2 project). It would be better if I would somehow just grant you access to my private repo

**Comment by urish** [comment]
Seems like this issue could be related: angular/angular#6005. 

Does it happen consistently?
Does calling `enableProdMode()` help?

**Comment by lordgreg** [comment]
@urish Just tested it with `enableProdMode()` and yes. The error is gone. However,... is that even smart thing to do while developing app? Or... can this error be avoided somehow?

**Comment by urish** [comment]
Good question :-) I will ping the team to see if they have any input about this

**Comment by MateuszG** [comment]
same here with ionic2

**Comment by urish** [comment]
Closing. If this still happens, please reopen

**Comment by djangojack** [comment]
@urish is there a way to avoid this error in dev mode or do we need to enable prod mode?

**Comment by jvelo** [comment]
@urish still happens, on 0.8.0
