### ISSUE TITLE
Support unix timestamp as input

### ISSUE THREAD

**Issue by lanocturne** [urish/angular2-moment#15]
It would be great if the amDateFormat  pipe or all pipes accept an unix timestamp(seconds) by argument configuration.

For example:
`{{1456263980 | amDateFormat: ['hh:mmA', true]}} -> 13:45PM`  
`true` means input is unix timestamp

**Comment by urish** [comment]
How about the same approach we used in [angular-moment](https://github.com/urish/angular-moment), providing a [`amFromUnix` filter](https://github.com/urish/angular-moment#amfromunix-filter) ?

**Comment by lanocturne** [comment]
Sounds good 👍

**Comment by urish** [comment]
Can you add this filter (as a new file, `FromUnixPipe.ts`) and send a PR ?

Things to note: 
1. Unit testing (should be pretty trivial for this pipe)
2. Updating README
3. Updating the list of files in package.json

Your contribution will be greatly appreciated!

**Comment by lanocturne** [comment]
Sure, I will make a PR tomorrow.
Uri Shaked <notifications@github.com>於 2016年2月23日 週二，下午2:17寫道：

> Can you add this filter (as a new file, FromUnixPipe.ts) and send a PR ?
>
> Things to note:
> 1. Unit testing (should be pretty trivial for this pipe)
> 2. Updating README
> 3. Updating the list of files in package.json
>
> Your contribution will be greatly appreciated!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/urish/angular2-moment/issues/15#issuecomment-187940749>
> .
>
-- 
Thanks,
Stanislaus

**Comment by urish** [comment]
Awesome, thanks!
