### ISSUE TITLE
Use of ng-packagr

### ISSUE THREAD

**Issue by pcdummy** [urish/angular2-moment#157]
Thanks for this great library.

@urish You might want to use [ng-packagr](https://github.com/dherges/ng-packagr) this make this library useable for AOT, FESM15, SystemJS and UMD loading.

I did this for ng2-ui-auth [here](https://github.com/ronzeidman/ng2-ui-auth/commit/b141d4eb39d05b467221d99d75494730f13873fa).

**Comment by urish** [comment]
Thanks for the feedback! Would you be willing to help by sending a Pull Request with this change?

Also, I presume this is a breaking change, correct?

**Comment by pcdummy** [comment]
No i won't be a breaking change, as its just a change of packaging with added importable formats.

I'll come with a PR soon.

**Comment by pcdummy** [comment]
Seems this moment.js and rollup which is used in ng-packagr aren't friends:

```
[UbuntuPro][~/Software/javascript/angular2-moment](venv-nodeenv)[master]->$ ./node_modules/.bin/ng-packagr -p ng-package.json -d
Building Angular library from ng-package.json

BUILD ERROR
Cannot call a namespace ('moment')
Error: Cannot call a namespace ('moment')
```

I tried various fixes including local patches on ng-packagr, but i can't get this to work atm. (no more time):

This might help: https://stackoverflow.com/questions/39519823/using-rollup-for-angular-2s-aot-compiler-and-importing-moment-js i like the moment-es6 solution.

**Comment by urish** [comment]
Thanks for looking into this!

Actually, I am not sure if we even need to include moment into the bundle - ideally, the user should be able to choose which moment.js version he wants to depend on

**Comment by urish** [comment]
See #191
