### ISSUE TITLE
How can i import amDateFormat pipe on angular cli unit test spec

### ISSUE THREAD

**Issue by mahmoud-nb** [urish/angular2-moment#165]
i use angular cli, and i want to define karma unit test spec. i have the following error " The pipe 'amDateFormat' could not be found" when run **ng test**

**Environment:**

Please answer the following questions:

* Angular version? 4.0.3
* TypeScript version? 2.1.0
* `moment` version? 2.17.1
* Are you using `moment-timezone`?  NO
* Are you using the angular-cli? YES
* Angular CLI version? 1.0.1
* Using Rollup/Webpack/System.js/Ionic/similar? NO

**Comment by aroller** [comment]
I had a similar problem when testing a component solved by:

```
...
beforeEach(async(() => {
    TestBed.configureTestingModule({
      declarations: [MyComponent],
      imports: [MomentModule],
...
```
and 

```
import { MomentModule } from 'angular2-moment';
```

**Comment by mahmoud-nb** [comment]
thx @aroller, it worked for me too
