### ISSUE TITLE
Use with Angular-CLI?

### ISSUE THREAD

**Issue by cquillen2003** [urish/angular2-moment#17]
How do you use angular2-moment with an Angular-CLI generated application?  I am getting the following errors after npm installing angular2-moment and importing a pipe:

[DiffingTSCompiler]: Typescript found the following errors:
  node_modules/angular2-moment/CalendarPipe.ts (4, 25): Cannot find module 'moment'.
  node_modules/angular2-moment/DateFormatPipe.ts (4, 25): Cannot find module 'moment'.
  node_modules/angular2-moment/TimeAgoPipe.ts (4, 25): Cannot find module 'moment'.

When trying to run 'typings install --save moment' I get the following the error:

-bash: typings: command not found

**Comment by urish** [comment]
Hi, can you try `node_modules/.bin/typings install --save moment` and see if this works?

**Comment by cquillen2003** [comment]
That worked.  Thank you!

Now, how do I use moment() in a component?

**Comment by urish** [comment]
If you need to use moment, use `import * as moment from 'moment';`

**Comment by cquillen2003** [comment]
import * as moment from 'moment' seems to work fine, but I'm getting errors when trying to use moment().  Do I need to inject the moment variable somehow?

The angular-moment library's README covers this use case.  Can you please provide a similar example for this version of the library?
