### ISSUE TITLE
Problems with moment 2.19.0

### ISSUE THREAD

**Issue by Schwobaland** [urish/angular2-moment#174]
**Description of the Issue and Steps to Reproduce:**

Did you search for duplicate issue? yes
Today was the relase of moment 2.19.0. There are some build issues with this angular2-moment and moment 2.19.0. The output is: 

```
Module not found: Error: Can't resolve './locale' in 'C:\angular-app\node_modules\angular2-moment\node_modules\moment\src\lib\locale'
resolve './locale' in 'C:\angular-app\node_modules\angular2-moment\node_modules\moment\src\lib\locale'
  using description file: C:\angular-app\node_modules\angular2-moment\node_modules\moment\package.json (relative path: ./src/lib/locale)
    Field 'browser' doesn't contain a valid alias configuration
  after using description file: C:\angular-app\node_modules\angular2-moment\node_modules\moment\package.json (relative path: ./src/lib/locale)
    using description file: C:\angular-app\node_modules\angular2-moment\node_modules\moment\package.json (relative path: ./src/lib/locale/locale)
      as directory
        C:\angular-app\node_modules\angular2-moment\node_modules\moment\src\lib\locale\locale doesn't exist
[C:\angular-app\node_modules\angular2-moment\node_modules\moment\src\lib\locale\locale]
 @ ./node_modules/angular2-moment/node_modules/moment/src/lib/locale/locales.js 65:16-60
 @ ./node_modules/angular2-moment/node_modules/moment/src/lib/locale/locale.js
 @ ./node_modules/angular2-moment/node_modules/moment/src/moment.js
 @ ./node_modules/angular2-moment/locale.pipe.js
 @ ./node_modules/angular2-moment/index.js
 @ ./src/app/master-data/master-data.module.ts
 @ ./src/$$_gendir lazy
 @ ./node_modules/@angular/core/@angular/core.es5.js
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://localhost:4200 ./src/main.ts

```

Please answer the following questions:

* Angular version? 4.4.4
* `moment` version? 2.19.0
* Are you using `moment-timezone`? no
* Are you using the angular-cli? yes

**Comment by arpit03187** [comment]
I am also getting the following error

`WARNING in ./~/moment/src/lib/locale/locales.js
Module not found: Error: Can't resolve './locale' in 'C:\Workspaces\node_modules\moment\src\lib\locale'
 @ ./~/moment/src/lib/locale/locales.js 65:16-60
 @ ./~/moment/src/lib/locale/locale.js
 @ ./~/moment/src/moment.js
 @ ./~/angular2-moment/date-format.pipe.js
 @ ./~/angular2-moment/index.js
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://localhost:4200 ./src/main.ts`

Angular versions - 
```
@angular/cli: 1.2.6
@angular/animations: 4.4.4
@angular/common: 4.4.4
@angular/compiler: 4.4.4
@angular/compiler-cli: 4.4.4
@angular/core: 4.4.4
@angular/forms: 4.4.4
@angular/http: 4.4.4
@angular/language-service: 4.4.4
@angular/platform-browser: 4.4.4
@angular/platform-browser-dynamic: 4.4.4
@angular/router: 4.4.4
@angular/cli: 1.2.6
```

**Comment by chapulina** [comment]
For a quick fix, locking the `angular2-moment` and `moment` versions worked for us:

~~~
    "angular2-moment": "1.3.3",
    "moment": "2.18.1",
~~~

**Comment by Schwobaland** [comment]
@chapulina your solution is not working here. We are working with yarn instead of npm and yarn adds moment (2.19.0) in a node_modules subfolder of angular2-moment. As a result i have two versions of moment in my project.

**Comment by lotoad** [comment]
add: 
`  "resolutions": {
    "moment": "2.18.1"
  }`
To your package.json and then install angular2-moment.

**Comment by Schwobaland** [comment]
@lotoad thanks! that worked for me.

**Comment by lonwi** [comment]
It works fine with latest moment 2.19.1 just in case
