### ISSUE TITLE
Exposing JS files instead of Typescript files

### ISSUE THREAD

**Issue by cschroeter** [urish/angular2-moment#18]
Unfortunately this module is exposing the Typescript files directly when it should only be the JS files

**Comment by urish** [comment]
@cschroeter both are exported as part of the npm package, which is the recommended way to consume this module.

You can install it by running `npm install --save angular2-moment`

**Comment by cschroeter** [comment]
Mh .. I'm using the ng2-webpack-starter and apparently - having both the Typescript file and the JS file available results in an "error" [#399](https://github.com/AngularClass/angular2-webpack-starter/issues/399)
Maybe you can have a look at the issue :)

**Comment by urish** [comment]
Thanks for the reference, I will comment on that issue
