### ISSUE TITLE
Issue integrating into angular2-seed

### ISSUE THREAD

**Issue by cviccaro** [urish/angular2-moment#19]
Hi, great module, but was having trouble getting it to work with angular2-seed (https://github.com/mgechev/angular2-seed) out-of-the-box.  I was getting a 404 error when SystemJS was trying to find moment.  For anyone using angular2-seed, and for @urish, only 1 line is needed to get it to work:

In tools/config/seed.config.ts, line 87, add the line between the comments:

```
  protected SYSTEM_CONFIG_DEV = {
    defaultJSExtensions: true,
// ADD THIS LINE
    packageConfigPaths: [`${this.APP_BASE}node_modules/*/package.json`],
//
    paths: {
      [this.BOOTSTRAP_MODULE]: `${this.APP_BASE}${this.BOOTSTRAP_MODULE}`,
      'angular2/*': `${this.APP_BASE}angular2/*`,
      'rxjs/*': `${this.APP_BASE}rxjs/*`,
      '*': `${this.APP_BASE}node_modules/*`
    },
    packages: {
      angular2: { defaultExtension: false },
      rxjs: { defaultExtension: false }
    }
  };
```

I'll post this in angular2-seed as well, since other modules may encounter the same issue.

**Comment by TheDonDope** [comment]
Hey there,

have you also installed the typings for angular2-moment as described in the [Installation](https://github.com/urish/angular2-moment#installation) section of the README? 

You do need to have `typings` installed as a global node module (`$ npm install -g typings`).

Greetings

Christian

**Comment by cviccaro** [comment]
Indeed, I did.  I have typings installed globally and moment's typings.  angular2-moment never threw a 404 or error, it was only moment itself.  I drew from this post to include the packageConfig option to get it working: https://github.com/urish/angular2-moment/issues/11#issuecomment-180819466
