### ISSUE TITLE
Cannot use in app due to triple-slash references

### ISSUE THREAD

**Issue by Nysosis** [urish/angular2-moment#2]
I'm trying to use this module, however my typescript stops transcribing after adding it, with the following message:

`[0] node_modules/angular2-moment/TimeAgoPipe.d.ts(1,1): error TS2654: Exported external package typings file cannot contain tripleslash references. Please contact the package author to update the package definition.`

Using Angular2 Beta.0

**Comment by urish** [comment]
Thanks for reporting this!

Can you please check if simply removing the `///` in the beginning of the file fixes this?
