### ISSUE TITLE
moment in others languages

### ISSUE THREAD

**Issue by victorcarvalhosp** [urish/angular2-moment#20]
It's possible to use moment in portuguese, for example? How I can do that? Thanks!

**Comment by urish** [comment]
Perhaps this will help:

First, import the moment module:

`import * as moment from 'moment';`

Then, inside your code, you can switch the locale, e.g.:

`moment.lang('pt-br');`

You can find the full list of moment locales here: https://github.com/moment/moment/tree/develop/locale

**Comment by numerized** [comment]
[solution here](https://github.com/moment/moment/issues/2608#issuecomment-235534993)
