### ISSUE TITLE
Cannot install it

### ISSUE THREAD

**Issue by pantonis** [urish/angular2-moment#21]
Hi,

Is it possible to add a very neat seed that only includes angular2-moment (systemjs) because I cannot install it as I get dozen of errors. Some of the errors:

Cannot find module 'moment'.

File 'C:/GIT/TestProj/TestProj.Web/node_modules/angular2-moment/TimeAgoPipe.ts' is not under 'rootDir' 'C:/GIT/TestProj/TestProj.Web/wwwroot/app'. 'rootDir' is expected to contain all source files.	

It is a pain in general words. A clear seed would highly appreciated

**Comment by urish** [comment]
Hi, there is an example with SystemJS in this plnkr:

http://plnkr.co/edit/ziBJ0mftSjnz0SrYPwbo?p=preview

Also, see these issues regarding SystemJS:

#19 
#11

**Comment by pantonis** [comment]
urish,

Thanks for the example but it doesn't work. I think remote scripts do not load

**Comment by urish** [comment]
Seems like `rawgit.com` is experiencing some problems:

![image](https://cloud.githubusercontent.com/assets/892318/13876050/36f3a6f0-ed0a-11e5-948c-d15af6bc4fa6.png)

I suggest to try again in an hour or so, hopefully they will resolve these issues

**Comment by pantonis** [comment]
I tried this in my own project with the cdn rawgit links and I still get 

File 'C:/GIT/TestProj/TestProj.Web/node_modules/angular2-moment/TimeAgoPipe.ts' is not under 'rootDir' 'C:/GIT/TestProj/TestProj.Web/wwwroot/app'. 'rootDir' is expected to contain all source files.

**Comment by urish** [comment]
Did you check out the solution proposed in #19 ?

**Comment by pantonis** [comment]
Yes, 

I have even install moment typings globally

**Comment by pantonis** [comment]
here is my system.config

`System.config({
            packages: {
                app: {
                    format: 'register',
                    defaultExtension: 'js'
                }
            },
            "map": {
                "angular2-moment": "https://rawgit.com/urish/angular2-moment/0.4.0"
            },
            "paths": {
                "moment": "https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.11.2/moment.js"
            },
            meta: {
                'moment': {
                    format: 'amd'
                }
            }
        });
        System.import('app/kernel/core.boot')
              .then(null, console.error.bind(console));`
