### ISSUE TITLE
Please excludes node_modules in the package

### ISSUE THREAD

**Issue by mkjeff** [urish/angular2-moment#23]
At this moment, releases ts source file is a good choose. but including angular2 module will break down the compatibility.

**Comment by urish** [comment]
`node_modules` should not be published with the npm package (see the `files` section of our [package.json](https://github.com/urish/angular2-moment/blob/79d1a18c417b87131a5b3ba525efd30c1bcb8ad4/package.json#L7)), but in some cases, `npm install` will create it inside the module folder.

**Comment by mkjeff** [comment]
thanks. how to avoid it?

**Comment by urish** [comment]
angular2 is now a peer dependency, which should fix this issue (see #24 for discussion)
