### ISSUE TITLE
Moment locale not woking

### ISSUE THREAD

**Issue by mauricionarcizo** [urish/angular2-moment#26]
Hi!

I'm trying use the moment and set the locale, but the language isn't  changing.
I set the language, as below:

moment.locale('pt-BR');

But the output is:

a few seconds ago

Version of Angular2-moment: 0.4.3
What I need do to work?

**Comment by urish** [comment]
Did you try all lower-case? see #20 

`moment.locale('pt-br');`

**Comment by mauricionarcizo** [comment]
Yes, I try and still don't translate.

**Comment by urish** [comment]
You may also need to load moment locales. See the following plunker for a working example:

http://plnkr.co/edit/Psu31oOcDf3RaHJIEwv5?p=preview

**Comment by mauricionarcizo** [comment]
Work!!
I did this:
import * as locales from 'moment/min/locales';

Thank you!

**Comment by urish** [comment]
thanks for sharing your solution :)

**Comment by WilldelaVega777** [comment]
I am using Ionic2 and have not been able to make it work, does anybody know how to change locales in a Ionic2 app?

**Comment by Yimiprod** [comment]
Same problem as @WilldelaVega777 on an ionic 2 project.
```
import * as moment from 'moment';

moment.locale('fr-fr');
```
Does nothing

**Comment by olavocneto** [comment]
@Yimiprod try

```js
import * as moment from 'moment';
import * as locales from 'moment/min/locales';

moment.locale('fr-fr');
```

**Comment by Yimiprod** [comment]
@olavocneto it say `canno't find module moment/min/locales` even if the the path to this part exist.

**Comment by victorcarvalhosp** [comment]
Didn't worked here too...

**Comment by cyberbobjr** [comment]
Same bug here : cannot find module moment/min/locales :(

**Comment by Yimiprod** [comment]
For ionic2 i had to create a fix in my app

app.ts
```typescript
import './patch/moment';
```

path/moment.ts
```
moment.locale('fr', { /* copy paste the local definition from the library */ }  as any);
```

**Comment by JacosNet** [comment]
just load moment with locales only and it's working:

"{{PATH}}/moment/min/moment-with-locales.min.js"

**Comment by cvett** [comment]
I have the Same Problem "cannot find module moment/min/locales" The solution not work.

**Comment by LekisS** [comment]
@cvett try this:

```
import * as moment from 'moment';
import 'moment/min/locales';

moment.locale('fr-fr');
```

**Comment by cvett** [comment]
@LekisS  Thanks its Works!

**Comment by Yimiprod** [comment]
@LekisS it works, thanks a lot.

**Comment by rodriguesgm** [comment]
i've tried all these solutions in Ionic2 RC0, but it seems that it doesn't work.
I'm getting:
Error in ./TimeAgo class TimeAgo - inline template:0:6 caused by: Cannot read property 'humanize' of undefined
ORIGINAL EXCEPTION: Cannot read property 'humanize' of undefined

is there something else to do?
thanks
