### ISSUE TITLE
Not found

### ISSUE THREAD

**Issue by be-codified** [urish/angular2-moment#27]
I have installed package with npm (also for typescript) and getting console error:

`Failed to load resource: http://localhost:5555/node_modules/moment/package.json the server responded with a status of 404 (Not Found)`

I can see the package inside of node_modules with name angular2-moment.

Here are my parts of code:

```
import { DateFormatPipe } from 'angular2-moment';
{{meeting.scheduled.start | amDateFormat:'LL'}}
```

What could be wrong?

**Comment by urish** [comment]
It is complaining about `moment` not found, so perhaps `npm install moment` will save the day.

Good luck!

**Comment by be-codified** [comment]
@urish thank you, it saved the day.
