### ISSUE TITLE
Internationalization support?

### ISSUE THREAD

**Issue by sklyukin** [urish/angular2-moment#3]
Is there a way to support internationalization currently?

**Comment by urish** [comment]
You can directly use `moment.locale()`. The `amTimeAgo` implantation uses moment.js methods, so it should respect the configured locale.

**Comment by sklyukin** [comment]
thx

**Comment by heitorfig** [comment]
Maybe I'm doing something wrong. But for me, using `moment.locale()` isn't working. This happens: "ReferenceError: moment is not defined". Am I missing something? By the way, I'm actually usign it in Ionic 2 Framework.

My header looks like this:
```javascript
import {Http, HTTP_PROVIDERS} from 'angular2/http';
import {Page, Geolocation, NavParams} from 'ionic/ionic';
import {TimeAgoPipe} from 'angular2-moment';
```

**Comment by urish** [comment]
Try adding:

`import * as moment from 'moment';`

to the list of your import statements. You may also need to install moment via npm by running `npm i -S moment`

**Comment by heitorfig** [comment]
Thank you urish!
It worked!

**Comment by victorcarvalhosp** [comment]
Someone can give one example of moment.locale() usage?

**Comment by sklyukin** [comment]
https://github.com/flaper/web/blob/master/src/main.ts#L64
