### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by m0hamed** [urish/angular2-moment#31]
The installation instructions are probably not enough (at least they were not enough for me). SystemJS does not know about angular2-moment and thus it doesn't work when it tries to load it at run time.

I had to add the following to the config object:

```
System.config({
  packages: {
    ... other packages here
,
    "angular2-moment": {
      main: "index.js",
      defaultExtension: 'js'
    }
  },
  map: {
    "angular2-moment": "/node_modules/angular2-moment",
  },
  paths: {
    "moment": "/node_modules/moment/moment.js"
  }
});
```

I am not an expert in systemJS or angular2 for that matter so If there is an easier way or if this was just localized to my installation then please tell me.

**Comment by urish** [comment]
Seems legit, through I am not a SystemJS expert myself. Any chance you can send a PR for the README with the SystemJS installation instructions?
