### ISSUE TITLE
Unable to implement in ionic 2 project

### ISSUE THREAD

**Issue by MatanYed** [urish/angular2-moment#33]
try it, it's makes alot of errors.
ionic 2 beta 6

if you success please tell me the steps to implement.

**Comment by danielgolub** [comment]
+1

**Comment by mauricionarcizo** [comment]
I'm using angular2-moment in my projeto ionic with success.
Steps to use:

npm install angular2-moment -> version 0.5.0 is compatible with ionic-angular beta 6

In my page/component declare the pipes, like this:

`
import {TimeAgoPipe} from 'angular2-moment/TimeAgoPipe.js';
@Component({
pipes:[TimeAgoPipe]
})
`
In my Html:

`
{{lastSync | amTimeAgo}}
`

**Comment by elineopsommer** [comment]
I followed the steps described by @mauricionarcizo , but i keep getting this error:
`/Users/Eline/Documents/Stack & Heap/project kvk app/kvkapp/node_modules/angular2-moment/TimeAgoPipe.ts:3
import {Pipe, ChangeDetectorRef, PipeTransform, OnDestroy} from 'angular2/core';
^
ParseError: 'import' and 'export' may appear only with 'sourceType: module'
`

**Comment by urish** [comment]
Should be fixed by 0.8.0. Just upgrade to latest angular2-moment and import it like this:

    import {TimeAgoPipe} from 'angular2-moment';

**Comment by elineopsommer** [comment]
This is not working for me.
i'm using: 
`"angular2": "2.0.0-beta.15",
    "angular2-moment": "^0.8.0",
"ionic-angular": "2.0.0-beta.6",`

**Comment by urish** [comment]
What does your import statement look like?

**Comment by elineopsommer** [comment]
The same like you said: `import {TimeAgoPipe} from 'angular2-moment';`

**Comment by urish** [comment]
And which error do you get?

**Comment by elineopsommer** [comment]
I get no errors anymore with the 0.8.0 version, but it also doesn't go to the page where I used the pipe in the html. I'll make a plunker.

**Comment by elineopsommer** [comment]
It works now, no clue why, I did everything again and now it works. Thanks.
