### ISSUE TITLE
angular2 rc0

### ISSUE THREAD

**Issue by sspilleman** [urish/angular2-moment#35]
Hi,

Can you please update to @angular/2.0.0-rc.0?

Thank you!!

**Comment by urish** [comment]
released as 0.7.0

**Comment by sspilleman** [comment]
please note there are breaking changes regarding pipes..... eg DateFormatPipe is broken now. You have to specify the format string like this now: amDateFormat:['MM DD YYYY'] (array braces around)

**Comment by urish** [comment]
Thanks @sspilleman, any chance you can help with a PR?

I am in ng-conf running a workshop so I won't have time to look into that myself today...

Thanks
