### ISSUE TITLE
angular2-moment map question

### ISSUE THREAD

**Issue by byunru** [urish/angular2-moment#36]
on the demo url: http://plnkr.co/edit/ziBJ0mftSjnz0SrYPwbo?p=preview
if I replace     "angular2-moment": "https://rawgit.com/urish/angular2-moment/0.6.0" with either of the following, none of them works,
1) "angular2-moment": "//cdn.rawgit.com/urish/angular2-moment/master"   
2) "angular2-moment": "//rawgit.com/urish/angular2-moment/master"
3) "angular2-moment": "//raw.githubusercontent.com/urish/angular2-moment/master"  

can you explain why?

**Comment by urish** [comment]
It is because of the packaging changes that are part of angular 2 beta 17. We need to align the example to use the latest rc of angular 2, this should fix this.

**Comment by urish** [comment]
The [plunker](http://plnkr.co/edit/ziBJ0mftSjnz0SrYPwbo?p=preview) example has just been updated to angular 2 RC 1,
