### ISSUE TITLE
outDir changes when importing angular2-moment

### ISSUE THREAD

**Issue by christiandreher** [urish/angular2-moment#37]
As soon as I use an import-statement to include a file as a pipe, my build scripts stop working properly.
If my code is in `/src`, and I want everything inside `/src` to be compiled to `/public` it works as expected without an import.
So for example, `/src/test.ts` becomes `/public/test.{map.}js`.
As soon as I import this module, it adds another directory (the `src` directory)
So `/src/test.ts` becomes `/public/src/test.{map.}js` suddenly...

Other projects seem to have similar problems. See this issue from ng2-bootstrap: https://github.com/valor-software/ng2-bootstrap/issues/128

Here is a Stackoverflow question, describing the very same problem I have (also, for ng2-bootstrap)
http://stackoverflow.com/questions/35648347/importing-ng2-bootstrap-changes-my-tsc-output-directory-structure

I hope this gets fixed soon, as I cant use this module if it messes up my whole directory structure...

_Edit_: I can confirm that this issue gets fixed if .ts (not .d.ts) files are moved into a separate directory

**Comment by urish** [comment]
Hi, just released 0.8.0, where the `.ts` files were moved to a separate directory, as you suggested. 

Can you please verify that this indeed solved your issue?

**Comment by christiandreher** [comment]
Thank you very much for the fix :) 
I will try it tomorrow and let you know then

**Comment by christiandreher** [comment]
Issue is resolved! Thank you very much for your quick fix
