### ISSUE TITLE
angular2-moment is not working with ionic2

### ISSUE THREAD

**Issue by MOHAMMADArsalan** [urish/angular2-moment#38]
I am using angular2-moment with ionic2.Its giving me error 
EXCEPTION: Error: Uncaught (in promise): No Pipe decorator found on TimeAgoPipe.

I import TimeAgoPipe as 
import {TimeAgoPipe} from "angular2-moment/TimeAgoPipe.js";
 Or
import {TimeAgoPipe} from "angular2-moment";

i both situation i m getting error

**Comment by urish** [comment]
Should be working with latest ionic beta (2.0 beta 25) and angular-moment 0.8.0. 

If still not working, please create a small git repo that reproduces the issue and reopen. Thanks!

**Comment by btdevn** [comment]
I am using ionic 2 beta 30, and I am receiving the same error.
