### ISSUE TITLE
Just one pipe?

### ISSUE THREAD

**Issue by HeathNaylor** [urish/angular2-moment#4]
Is there only the time ago pipe right now? Does this need contributions?

**Comment by urish** [comment]
Yes, only time ago at the moment. Contributions are always appreciated!

Are there any other pipes that you need?

**Comment by HeathNaylor** [comment]
I guess I would need to know the intended scope of this package. If would this completely wrap around moment and use pipes for things like formatting or is it intended to be used for more edge case manipulations?

**Comment by urish** [comment]
Summarizing some of the leanings from `angular-moment`, it seems like formatting and timezone related functions are also valuable.

I always like to see if a specific feature is valuable to some users before developing it, so user needs greatly shape the set of features in the library.

That's also why I asked whether there is something particular that you need...

**Comment by HeathNaylor** [comment]
Formatting was the one I was looking for specifically.

**Comment by urish** [comment]
Something like `{{myDate | amDateFormat:'MM.DD.YYYY HH:mm:ss'}` ?

**Comment by HeathNaylor** [comment]
Yea, that would work. This brings up interesting questions about the use of moment in angular. Would we be using the pipe system to generate moment objects that we then send into other moment pipes or would we simple use javascript native date objects and only use moment for display of the native date objects?

I am needing to take today's date and set it to the beginning of the day. This would be easy with a angular pip of `{{myDate | amStartOf:'day'}}` but I would need the then start a counter every second to get the HH:mm:ss output I am looking for and then pass that into `{{myMomentDate | amDateFormat:'HH:mm:ss}}`.

The alternative is to use js native date and just do:
```
var start = new Date();
start.setHours(0,0,0,0);

{{start | amDateFormat:'HH:mm:ss'}}
```

How do you envision moment being used within a more complex date oriented application?

**Comment by urish** [comment]
This is a good question. Based on my experience from `angular-moment`, a set of composable pipes can make a lot of sense.

In general, we have 3 types of pipes there:

1. Convert arbitrary value into a `moment()`. e.g. parsing a moment from a given string, like `amParse` does.
2. Manipulate an existing `moment()` object and return a new one, e.g. adding or subtracting time.
3. Converting a `moment()` to user readable format. `amTimeAgo`, `amDateFormat` and `amCalendar` come into mind.

I think we can start by implementing `amDateFormat`. In any case, all of the methods can supporting getting a native `Date` object as input.

Thoughts?

**Comment by HeathNaylor** [comment]
I am good with starting with just native `Date` objects for the time being. Moving forward should we have all of the methods support both native `Date` objects and `Moment` objects or should we have specific methods for `Moment` objects  and different methods for `Date` objects. Seems to me that `amTimeAgo` should work off both `Date` and `Moment` objects.

**Comment by urish** [comment]
Yes, that makes sense to me. If you can help with contributing `amDateFormat` (+ relevant unit tests) that will be awesome!

**Comment by HeathNaylor** [comment]
I have already started on that and will do more tonight. Forgive my lack of experience, I am new to Angular 2. Can you only use Pipes from within the component template (HTML) or is it possible to use them from within the component class itself?

**Comment by urish** [comment]
Questions are always welcome :)

Pipes are intended to be used from template. Nothing is stopping you from creating an instance of the class directly within Javascript and call the methods (that's what we do in the unit-tests), though, in this case, you can simply call `moment` methods directly inside your Component class - there is no need to go through the pipe. Does this make sense to you?

**Comment by HeathNaylor** [comment]
Makes sense to me. Would we then need to import moment into any component that intends to use it? Moving further conversation of this into a gitter room for now unless you want to keep the log here. https://gitter.im/HeathNaylor/angular2-moment

**Comment by urish** [comment]
So we already have a `amCalendar` pipe (#6) :-)
