### ISSUE TITLE
support of undefined date

### ISSUE THREAD

**Issue by dohomi** [urish/angular2-moment#41]
Hello @urish 
thanks for this package. I have a user-list where deeply nested the property of the date value is stored:
`user.state.lastLogin.date`. Inside the `ngFor` not all dates are set - is it possible to set the undefined string to `""` as empty string? Thanks

**Comment by urish** [comment]
Yes, this makes sense. Can you please send us a PR for that?

**Comment by amcdnl** [comment]
@urish - happy to assist w/ this. Can you point me in direction?
