### ISSUE TITLE
Translating the pipe output

### ISSUE THREAD

**Issue by theunreal** [urish/angular2-moment#43]
Is it possible to translate to another language the pipe output?

For example, changing "X Hours ago" to another language?

**Comment by urish** [comment]
Yes, though moment's locale support:

https://github.com/moment/momentjs.com/blob/master/docs/moment/06-i18n/01-changing-locale.md

**Comment by theunreal** [comment]
@urish Are you sure this documentation works with this module? I've been trying to use `moment.locale('fr');` after importing `import * as moment from 'moment';` but the language locale is still English.

**Comment by urish** [comment]
You may also need to loaded locale files, as explained here:
http://momentjs.com/docs/#/i18n/loading-into-browser/

Do you get English or French output when you call `moment().fromNow()`?

**Comment by theunreal** [comment]
thanks @urish, I didn't load the locale file - but I have no idea how to load it after `moment` is loaded, since I'm using SystemJS.
When I output moment().fromNow() I get `Error: TypeError: moment is not a function` as described in my last post

**Comment by urish** [comment]
You can try to `import `moment/locale/fr` after importing moment and see if this does the trick. 
Anyway, it sounds weird that you are not able to call `moment()` despite being able to call `moment.locale('fr')` - I suggest that you post a question on StackOverflow about that.

**Comment by theunreal** [comment]
The import you suggested worked, Thanks!

**Comment by urish** [comment]
:+1:

**Comment by 560889223** [comment]
Kudos on `import "moment/locale/fr"`

I was just struggling to figure out how to import a JS file into TS source
