### ISSUE TITLE
“Expression has changed after it was checked”

### ISSUE THREAD

**Issue by theunreal** [urish/angular2-moment#44]
the details are here
http://stackoverflow.com/questions/37884709/angular-2-expression-has-changed-after-it-was-checked

Any fix?

**Comment by doczoidberg** [comment]
did you found a solution? The stackoverflow answer doesn't fix it

**Comment by theunreal** [comment]
Yes, it does work on production mode. just enable the prod mode.

**Comment by doczoidberg** [comment]
that is no real solution
