### ISSUE TITLE
Angular exception

### ISSUE THREAD

**Issue by bzums** [urish/angular2-moment#48]
I got the following error which I guess is related to the angular-moment pipe:
```
ORIGINAL EXCEPTION: Expression has changed after it was checked. Previous value: '
          (session expires in 21 minutes)
        '. Current value: '
          (session expires in 20 minutes)
```

Ad hoc any ideas? I will later debug in more depth and add some context.

**Comment by bzums** [comment]
This could be related:
http://www.syntaxsuccess.com/viewarticle/timeouts-and-timerwrapper-in-angular-2.0

**Comment by urish** [comment]
Duplicate: #44, #14, #42

**Comment by urish** [comment]
Can you please create a small plunker example the reproduces the issue?

**Comment by bzums** [comment]
@urish the problem is that I dont know how to reproduce it exactly, it seems to be a timing issue and  seems to occur very very rare. My suggestion would be to replace the `setTimeout` calls with the `TimerWrapper` but it is just a guess...

**Comment by urish** [comment]
Hi, can you please check if this fixes the issue for you?

https://github.com/urish/angular2-moment/blob/issue-48/src/TimeAgoPipe.ts

Thanks!

**Comment by ivoviz** [comment]
@urish Although you asked @bzums, I've checked and it seems the problem goes away with the `issue-48` branch. Imho merge and release! :)

**Comment by urish** [comment]
Thanks @ivoviz !

Can you please describe how you checked it?

**Comment by ivoviz** [comment]
@urish Basically I have a site where I use `amTimeAgo` 50+ times / page. When I have that many elements and the times are between 0-60 minutes ago (so they *should* change approx. every minute) the errors occur really easily, basically every minute, or even more often. Using your patch I've left the site there for half an hour and it's still functioning, not a single error.

**Comment by urish** [comment]
Thanks @ivoviz ! And are all the timers updating as they should?

**Comment by ivoviz** [comment]
I'm not sure about that, it seems like there are cases when the timers don't update, I'll see if I can reproduce.

**Comment by ivoviz** [comment]
@urish Actually the timers never update on their own, sadly. Unless there's an other change, they stay exactly the same.

**Comment by urish** [comment]
@ivoviz Thanks for the input! For now we will not merge the PR, at least until there is a good solution for the timers not updating problem.

**Comment by AurelieV** [comment]
@ivoviz @urish juste add cdr.detectChanges() in the timeOut callback and it will normally works :)
I have the same case as @ivoviz (lot of components inferior to one minute) and it works for me.

```
this._currentTimer = window.setTimeout(() => {
     this._cdRef.markForCheck();
     this._cdRef.detectChanges();
 }, timeToUpdate);
```
Can you please test it, and I will be glad to add a PR if it works for everybody

**Comment by ivoviz** [comment]
@AurelieV I would gladly test this, just a quick question before: Is this change based on the master, or #55?

**Comment by AurelieV** [comment]
@ivoviz on master

**Comment by ivoviz** [comment]
@AurelieV Doesn't seem to work for me, the error is still happening.

**Comment by AurelieV** [comment]
@ivoviz Damn. I think it is still the way to explore, just find the good time to call it :s.

**Comment by josx** [comment]
I have read and all doc talks about calling detectChanges() as @AurelieV code.
can someone do a pluckr with the example of the problem? I would be great to track the problem and possible fixes.

Just for the record:
https://github.com/michaelbromley/ng2-pagination/issues/69
https://github.com/angular/angular/issues/6005

**Comment by urish** [comment]
Not sure if this still happens with angular 2.0.1. If relevant, please reopen.
