### ISSUE TITLE
Update to Angular 2 rc.4

### ISSUE THREAD

**Issue by Aamir-Shah** [urish/angular2-moment#49]
Can you please update to @angular/2.0.0-rc.4?

Thank you!! :)

**Comment by Aamir-Shah** [comment]
Can you please update to @angular/2.0.0-rc.4?

Thank you!! :)

**Comment by urish** [comment]
Is there any reason why the current version does not work with RC 4?

**Comment by Aamir-Shah** [comment]
I don't know, maybe it's because of Breaking Changes in RC 4

**Comment by urish** [comment]
I just checked it, it seems to work well with RC.4, you can see an example on this plunker:

http://plnkr.co/edit/ziBJ0mftSjnz0SrYPwbo?p=preview

Is there any specific error message that you are getting when you are trying to use it with rc 4 ?

**Comment by Aamir-Shah** [comment]
Console showing 404 error for Angular2-moment, but i have installed it already:
`(index):23 Error: Error: XHR error (404 Not Found) loading http://localhost:3000/angular2-moment
	    at XMLHttpRequest.wrapFn [as _onreadystatechange] (http://localhost:3000/node_modules/zone.js/dist/zone.js:769:30)
	    at ZoneDelegate.invokeTask (http://localhost:3000/node_modules/zone.js/dist/zone.js:356:38)
	    at Zone.runTask (http://localhost:3000/node_modules/zone.js/dist/zone.js:256:48)
	    at XMLHttpRequest.ZoneTask.invoke (http://localhost:3000/node_modules/zone.js/dist/zone.js:423:34)
	Error loading http://localhost:3000/angular2-moment as "angular2-moment" from http://localhost:3000/app/viewTodo/viewTodo.component.js(anonymous function) @ (index):23ZoneDelegate.invoke @ zone.js:323Zone.run @ zone.js:216(anonymous function) @ zone.js:571ZoneDelegate.invokeTask @ zone.js:356Zone.runTask @ zone.js:256drainMicroTaskQueue @ zone.js:474ZoneTask.invoke @ zone.js:426
stats.js:100Font Awesome CDN reporting has been enabled`

**Comment by urish** [comment]
Thanks for the info, this is not related to the Angular version, rather to your system configuration. You can try see how we load angular2-moment in the plunker, or also have a look at #31, #21, #19 and #11 which may contain helpful information.
