### ISSUE TITLE
Performance issue

### ISSUE THREAD

**Issue by andreialecu** [urish/angular2-moment#5]
I'm trying to convert an app using `ng-upgrade` from angular1 to angular2, and I noticed that adding the `amTimeAgo` pipe to one of my pages completely kills the performance. 

The pipe is used in a section  that is below a `*ngFor`. Upon JS profiling, I noticed that the `transform` method of this pipe is being called repeatedly, every tick, completely killing performance for the page.

I stepped through the code trying various things, and setting the pipe as `pure` fixes this, but it probably kills the dynamic update functionality.

Any ideas what could be wrong?

**Comment by andreialecu** [comment]
Adding `changeDetection: ChangeDetectionStrategy.OnPush` to my Component seems to fix this, but this seems pretty intrusive and I have to do some things differently because of it.

**Comment by urish** [comment]
@andreialecu thanks for reporting! Any chance you could create a quick plunker that reproduces the issue?

**Comment by andreialecu** [comment]
@urish Here's the repro: http://plnkr.co/edit/rHGx6CoX2lKy6WVFMkFI?p=preview

However, this looks like an angular2 bug. I reported it here: https://github.com/angular/angular/issues/6245#issuecomment-168732222

**Comment by andreialecu** [comment]
I will close this since it is not this component's fault.

**Comment by urish** [comment]
Thanks for all your contributions, much appreciated!
