### ISSUE TITLE
Pipes should allow us to ad a third parameter to define the entrie data format.

### ISSUE THREAD

**Issue by Yimiprod** [urish/angular2-moment#52]
In moment.js documentation, we are allowed to specify [the data format](http://momentjs.com/docs/#/parsing/string-format/) in case the date isn't `ISO 8601` formated.

Is it possible to implement this?

**Comment by urish** [comment]
Something like [amParse](https://github.com/urish/angular-moment#amparse-filter) from angular-moment?
