### ISSUE TITLE
Pipes should not be prefixed with 'am'

### ISSUE THREAD

**Issue by awexfwex** [urish/angular2-moment#53]
The prefixing of pipes with 'am' seems unnecessary, given pipes are included explicitly in components. Additionally, given the word 'am' is relevant to time already, it is confusing/misleading. 

Also, dat's 2 xtra chars u got 2 typ.

**Comment by urish** [comment]
Thanks for sharing, interesting thought. 

Actually, there is another reason we are using the am prefix, to keeping the convention we used it [angular-moment](https://github.com/urish/angular-moment). I don't think the two extra characters are such a big deal though, but if we see too many people are confused by the am prefix, I may consider changing it.

**Comment by Gp2mv3** [comment]
I agree on the fact that "am" is confusing at first...
I took some minutes to understand that it stands for Angular Moment.

**Comment by DaSchTour** [comment]
I think that with a simple "hack" it could be possible to support both.
As TypeScript allows extending. It's possible to create two Pipe classes with the same functionality but with different names.
With the new modules introduced with RC5 selecting the preferred variant is also easy.
I could make the necessary changes and create a pull request.

**Comment by urish** [comment]
Thanks everyone for their comments! For now, we will stick with the `am` prefix.
