### ISSUE TITLE
Update peer dependencies to Angular rc 4

### ISSUE THREAD

**Issue by joshgarwood** [urish/angular2-moment#58]
Current the peer dependencies target a fixed Angular rc.0 reference, which makes it such that this package can't be used in the latest version of Ionic 2, which targets RC 4.  Or, better yet, make this an unfixed peer dependency so there won't be conflicts in the future (if that's possible).

Thanks!

**Comment by urish** [comment]
Hi, the peer deps specify `"@angular/core": "^2.0.0-rc.0"` which means it should be compatible with 2.x.x (including all later rc versions).

You can read more about it here: http://bytearcher.com/articles/semver-explained-why-theres-a-caret-in-my-package-json/
