### ISSUE TITLE
Can't find variable: window

### ISSUE THREAD

**Issue by ahmedelgendy** [urish/angular2-moment#59]
Implementing this code example:
```
import {TimeAgoPipe} from 'angular2-moment';
@Component({
  selector: 'app',
  pipes: [TimeAgoPipe],
  template: `
    Last updated: <time>{{myDate | amTimeAgo}}</time>`
})
```
throws this error:
```
CONSOLE LOG file:///app/tns_modules/@angular/core/src/facade/lang.js:345:16: ORIGINAL E
XCEPTION: ReferenceError: Can't find variable: window
```
where is the problem?

**Comment by urish** [comment]
Seems like a configuration error with your setup. You can try the online [plunkr example](http://plnkr.co/edit/ziBJ0mftSjnz0SrYPwbo?p=preview), or start with a working seed (such as [angular2-seed](https://github.com/mgechev/angular2-seed) or [angular2-webpack-starter](https://github.com/AngularClass/angular2-webpack-starter))

**Comment by ahmedelgendy** [comment]
I am working on a nativescript project
