### ISSUE TITLE
Update to ngModule (angular RC5) 

### ISSUE THREAD

**Issue by stocksr** [urish/angular2-moment#60]
https://angular.io/docs/ts/latest/guide/ngmodule.html

**Comment by urish** [comment]
Hi,
Can you help by sending a pull request for that?

I believe that a good approach would be to still let specific pipes to be individually imported, as well as providing an ngModule which contains all the pipes.

**Comment by stocksr** [comment]
not 100% sure I have got everything correct but it seems to work for me.  Let me know if you want anything changed
