### ISSUE TITLE
 Unhandled Promise rejection: Template parse errors: The pipe 'amTimeAgo' could not be found 

### ISSUE THREAD

**Issue by gvsdan** [urish/angular2-moment#62]
I followed the instructions for the angular RC5 update but i get this in one of my templates.

**Comment by urish** [comment]
Hi Dan,

Are you using angular 2 rc5?

Did you include MomentModule in your imports?

**Comment by gvsdan** [comment]
@urish  yes but maybe i'm doing something wrong i'm not doing this in the root module but in a feature module so should i add the MomentModule in the imports of that module and then add the feature module to the root?

**Comment by gvsdan** [comment]
@urish  Sorry dude i did that and now its working thanks <3

**Comment by gvsdan** [comment]
Sorry i'm still having the this issue.

**Comment by Balbo76** [comment]
Similar problem ...
