### ISSUE TITLE
changing locale not working in the latest version

### ISSUE THREAD

**Issue by theunreal** [urish/angular2-moment#65]
Did:

```
import * as moment from 'moment';
moment.locale('he');

```

in my app module.ts
but locale doesn't change

**Comment by urish** [comment]
See #26

**Comment by codeggercom** [comment]
I have same problem. Nothing does not change. Everthings is working but 'locale function' is not defined.

**app.module.ts**
import {MomentModule} from 'angular2-moment';
import * as moment from 'moment';
import 'moment/min/locales';

constructor(){
   moment.locale('tr');
}
