### ISSUE TITLE
Update to angular RC6  ?

### ISSUE THREAD

**Issue by rousdan** [urish/angular2-moment#67]
any plans to update angular2-moment to the current Release Candidate?

**Comment by urish** [comment]
Hi, is there anything specific not working with RC6?

**Comment by kirbyt** [comment]
> Hi, is there anything specific not working with RC6?

I updated to RC6 today and now I get this error message:

> main.ts:13Error: Template parse errors:
> 'time' is not a known element:
> 1. If 'time' is an Angular component, then verify that it is part of this module.
> 2. If 'time' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schema' of this component to suppress this message.

While digging around I found this [comment](https://github.com/angular/angular/issues/11251#issuecomment-244255512) that says "starting with RC6 Angular2 enforces that tags name are valid." See the comment for more details.

I'm an Angular 2 novice, so I don't have a solution to the problem yet.

**Comment by urish** [comment]
Hi, just replace the `<time>` tag with a `<span>`, and it should fix the issue:

    <span>{{myDate | amTimeAgo:true}}</span>

If you have a few moments to send a pull request for the README with this fix, that would be great!

**Comment by kirbyt** [comment]
Thanks, @urish.

I confirmed that replacing the `<time>` tag with`span` works. In fact, `span` isn't even needed. 

I'll send you a PR for the README shortly.

Thanks again.
