### ISSUE TITLE
how do we access the underline raw moment()?

### ISSUE THREAD

**Issue by born2net** [urish/angular2-moment#69]
how do we access the underline raw moment()?
it's nice to have the pipes etc...
but what about just accessing the raw instance of moment so we get access to all its goodness?

tx

Angular 2 Kitchen sink: http://ng2.javascriptninja.io
and source@ https://github.com/born2net/ng2Boilerplate
Regards,

Sean

**Comment by christiandreher** [comment]
You don't need `angular2-moment` to use `moment`. Nothing prevents you from doing:

```typescript
import * as moment from 'moment';
moment.locale('en-US'); // Or whatever you wanna do
```

**Comment by born2net** [comment]
hi, 
I figured why import 2 libs when one can do both.
regards
(toda)
sean - https://github.com/born2net/ng2Boilerplate

**Comment by christiandreher** [comment]
`angular2-moment` just has to be imported once in the `app.module.ts`. If you need library features inside the code, you'll have to import it anyway.

**Comment by born2net** [comment]
tx
