### ISSUE TITLE
npm ERR! 404  '@types/angular2-moment' is not in the npm registry.

### ISSUE THREAD

**Issue by jaufgang** [urish/angular2-moment#79]
Sorry to bug you, but npm _explicitly_ told me to bug you.

In particular, when i try to download the typings using `$ npm install @types/angular2-moment --save-dev --save-exact`, i get the following message:

```
npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "@types/angular2-moment" "--save-dev" "--save-exact"
npm ERR! node v6.6.0
npm ERR! npm  v3.10.3
npm ERR! code E404

npm ERR! 404 Not found : @types/angular2-moment
npm ERR! 404 
npm ERR! 404  '@types/angular2-moment' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
```

I need to install the typings using the npm @types registry in order to get this module to work with the latest ionic 2 rc0, which uses Rollup and expects typings to be installed this way instead of using tsd (see https://github.com/driftyco/ionic/blob/master/CHANGELOG.md#typings and https://blogs.msdn.microsoft.com/typescript/2016/06/15/the-future-of-declaration-files/).  

Thanks!

**Comment by urish** [comment]
Hi, the types are already included in the `angular2-moment` npm package - there is no need for separate installation.
