### ISSUE TITLE
Typescript error: no exported member 'MomentModule'

### ISSUE THREAD

**Issue by ganySA** [urish/angular2-moment#80]
Hi

I have installed angular2-moment and i seem to be getting an error:

angular2-moment has no exported member 'MomentModule' ?

Thanks

**Comment by ganySA** [comment]
When i look at the version i get from npm and i open index.ts it does not have and export for "module" as per the source code here - is the latest version published to npm?

**Comment by ganySA** [comment]
Ok so i resolved the initial issue by installing the latest version on npm using @1.0.0-beta.1

However now i have the issue of index.js does not export DateFormatPipe?

**Comment by urish** [comment]
Hi, simply import it like this:

    import { MomentModule } from 'angular2-moment/module';

**Comment by urish** [comment]
Also see #68 if you are using AoT
