### ISSUE TITLE
404 error while loading library

### ISSUE THREAD

**Issue by smartm0use** [urish/angular2-moment#83]
Hello, i get the following error when i run my app:

    GET http://localhost:3000/angular2-moment/index.js 404 (Not Found)
    Error: Error: XHR error (404 Not Found) loading http://localhost:3000/angular2-moment/index.js
	    at XMLHttpRequest.wrapFn [as _onreadystatechange]     (http://localhost:3000/node_modules/zone.js/dist/zone.js:636:29)
	    at ZoneDelegate.invokeTask (http://localhost:3000/node_modules/zone.js/dist/zone.js:225:37)
	    at Zone.runTask (http://localhost:3000/node_modules/zone.js/dist/zone.js:125:47)
	    at XMLHttpRequest.ZoneTask.invoke     (http://localhost:3000/node_modules/zone.js/dist/zone.js:293:33)
	Error loading http://localhost:3000/angular2-moment/index.js as "angular2-moment" from     http://localhost:3000/app/app.module.js

Here is my configuration in `systemjs.config.js`

    var map = {
        'app': 'app',
        '@angular': 'node_modules/@angular',
        'rxjs': 'node_modules/rxjs',
        'moment': 'node_modules/moment',
        'angular-2-moment': 'node_modules/angular2-moment'
    };

    var packages = {
        app: { main: 'main.js',  defaultExtension: 'js' },
        rxjs: { defaultExtension: 'js' },
        moment: { main: './moment.js', defaultExtension: 'js' },
        'angular2-moment': { main: './index.js', defaultExtension: 'js' }
    };

Then i have this in `app.module.ts` file:

import {MomentModule} from 'angular2-moment';

    @NgModule({
        imports: [
            MomentModule
        ]
    })

What could be the problem?
Thank you.

**Comment by urish** [comment]
Perhaps the perform is the extra dash in your system is config:
`angular-2-moment`

**Comment by smartm0use** [comment]
Doh!
