### ISSUE TITLE
Ionic2 rc issue - ngc error: Error: Unexpected value 'MomentModule' imported by the module 'AppModule'

### ISSUE THREAD

**Issue by fuggfuggfugg** [urish/angular2-moment#85]
Using this library with the latest Ionic2 RC version. When running the emulator I get the above error.

Similar issue - https://github.com/gevgeny/angular2-highcharts/issues/75

**Comment by urish** [comment]
Please use the following import statement:

    import { MomentModule  } from 'angular2-moment/module';

This has something to do with rollup configuration in Ionic.

**Comment by balasivagnanam** [comment]
I am using the above but still getting the same error.

```
import {MomentModule} from 'angular2-moment/module';
//import {DateFormatPipe, CalendarPipe} from 'angular2-moment';


@NgModule({
  declarations: [
    MyApp,
    HomePage,
    AccountPage,
    ContestPage,
    EditMemberPage,
    EventDetailsPage,
    EventsPage,
    EventsTabsPage,
    LibraryPage,
    LoginPage,
    MagazinePage,
    MyEventsPage,
    RegisterEventPage,
    VolunteerPage,
    MomentModule,
    OrderBy
  ],
```

> Uncaught Error: Unexpected module 'MomentModule' declared by the module 'AppModule'(anonymous function) @ metadata_resolver.js:275CompileMetadataResolver.getNgModuleMetadata @ metadata_resolver.js:262RuntimeCompiler._compileComponents @ runtime_compiler.js:126RuntimeCompiler._compileModuleAndComponents @ runtime_compiler.js:64RuntimeCompiler.compileModuleAsync @ runtime_compiler.js:55PlatformRef_._bootstrapModuleWithZone @ application_ref.js:302PlatformRef_.bootstrapModule @ application_ref.js:284(anonymous function) @ main.dev.js:3(anonymous function) @ main.dev.js:3

**Comment by urish** [comment]
Have your tried with today's release (beta 3)?

**Comment by pisix** [comment]
@balasivagnanam 
 Upgrade to the latest release 1.0.0-beta.3 and 
```
import { BrowserModule  } from '@angular/platform-browser';
import {MomentModule} from 'angular2-moment';
@NgModule({
    declarations:[/**...**/]
    imports:      [BrowserModule,MomentModule],
	bootstrap:    [AppComponent],
    providers:[
       /**
	   ...
	   
	   **/
    ]
})

```

**Comment by balasivagnanam** [comment]
This works.. thanks a lot guys, I just realised there was update published few hours after I downloaded this.
