### ISSUE TITLE
CalendarPipe is not pure

### ISSUE THREAD

**Issue by moxival** [urish/angular2-moment#88]
Hi, first of all thanx for this awesome library - it helps a lot :)

Is there a possibility for you to add a pure version of CalendarPipe, this will really help performance-wise when we do not really need to track the changes?

**Comment by urish** [comment]
Thanks for the positive feedback!

At the moment this is not something we are going to add, currently the focus is on shipping a stable 1.0 release and not adding new features.

If there is a good use-case backed up by numbers (e.g. showing that CalendarPipe as actually a performance bottleneck in some app), will consider adding a PureCalendarPipe in the future.

**Comment by moxival** [comment]
OK, thanks for the comment :)
