### ISSUE TITLE
Module or jsnext:main in package.json

### ISSUE THREAD

**Issue by danbucholtz** [urish/angular2-moment#90]
Since this is a Typescript app, can you distribute `es5` code (es5 target) with `es2015` modules in addition to the `commonjs` modules you distribute?

Set the `moduleResolution` to `node` as well to make everything work well in the `tsconfig.json`.

`jsnext:main` and `module` are the fields that point to the entrypoint for the es5 code with es2015 modules. Angular uses `module` and it seems most bundlers look for `module`, then `jsnext:main`, then `main` in that order.

Thanks,
Dan

**Comment by urish** [comment]
Hi Dan,

Can you please send a PR for that?

Thanks!

**Comment by danbucholtz** [comment]
@urish,

Sorry, I cannot at this time. I submitted this issue to about 10-15 libs that we're seeing Ionic users use that don't follow this pattern. I don't have time, I am swamped with Ionic right now, but if you have any questions I can help as I have done this a few times now.

Thanks,
Dan

**Comment by urish** [comment]
@danbucholtz can you perhaps point me at another lib which has already implemented this? 
I'm curious about the build process for producing both es5 and es5+esnext modules bundles.

**Comment by danbucholtz** [comment]
Yes, definitely. Ionic 😄 

This file covers the build portion of it.
https://github.com/driftyco/ionic/blob/master/scripts/gulp/tasks/build.ts

We create a temporary `tsconfig.json` for our build process depending on what step we're in.
https://github.com/driftyco/ionic/blob/master/scripts/gulp/util.ts#L35

Our `package.json` looks like this:
https://github.com/driftyco/ionic/blob/master/scripts/npm/package.json#L12

Let me know if you have any questions. It is kind of a lot to take in in someone else's repo to understand what's going on.

Thanks,
Dan

**Comment by urish** [comment]
Should be fixed once #191 lands
