### ISSUE TITLE
configure amCalendar

### ISSUE THREAD

**Issue by iBasit** [urish/angular2-moment#95]
How can I configure `Last updated: <time>{{myDate | amCalendar}}</time>`, so it does not display 'L' format (08/17/2016). for everything else date, I want it to display date in words like 'LL h:mm A' format.

is it possible?

**Comment by iBasit** [comment]
```
import * as moment from 'moment';

moment.locale('en', {
    calendar : {
        lastDay : '[Yesterday at] LT',
        sameDay : '[Today at] LT',
        nextDay : '[Tomorrow at] LT',
        lastWeek : '[last] dddd [at] LT',
        nextWeek : 'dddd [at] LT',
        sameElse : 'LL [at] h A'
    }
});

```

**Comment by gobalistik** [comment]
just in case anyone else finds this

{{notification?.created?.toDate() | amCalendar:{sameDay:'HH:mm', lastDay:'[Yesterday at] HH:mm', lastWeek:'DD MMM', sameElse:'DD MMM'} }}
