### ISSUE TITLE
Locale change not working since upgrade to Module

### ISSUE THREAD

**Issue by kghaghada** [urish/angular2-moment#97]
I've recently upgraded a project to angular 2 final and found that a locale change on moment doesn't change the displayed lang using am pipes.

I've used the suggestions from [#26](https://github.com/urish/angular2-moment/issues/26) but still have the issue.
`import * as moment from 'moment';`
`import 'moment/min/locales';`

I've created an example here: [plunkr](http://plnkr.co/edit/hDNzVLKoKpQQICWV1vWk?p=info)

**Comment by mariolenis** [comment]
Hi, 

At `packages` use `moment/min/moment-with-locales.min.js`, then:

`import * as moment from 'moment';`
`.`
`.`
`.`
`export class MyComponent {`
`       constructor() {`
`              moment.locale('<your laguage>');`
`       }`
`}`

**Comment by rafalkasa** [comment]
Hi

I'm using current version with angular2 NgModule and for me everything is working.
If you want to use different locale you should import in your class eg. **app.component.ts**

```
import * as moment from 'moment';
import 'moment/locale/pl';

    constructor() {   
        moment.locale('pl'); 
    }
```
Please look at closed issue #20

**Comment by kghaghada** [comment]
As can be seen in the plunkr example I attached to the original issue description, I am doing exactly as suggested. 

`import * as moment from 'moment';`
`import 'moment/min/locales';`
`.`
`.`
`class TimeagoDemoComponent {`
`	constructor() {`
`		this.lastUpdated = new Date();`
		
`                moment.locale('de')`
`	}`

However, the lang is always defaulting to en.
Even when toggling the lang on clicking a button, it remains en.

Feel free to point out if/where the plunkr example is incorrect

**Comment by urish** [comment]
Seems like adding the following line into the `packages` section of your System.js configuration does the trick:

    'moment':          'https://npmcdn.com/moment@2.14.1',

You can find an updated / working plunker here:

http://plnkr.co/edit/kDLaYBLblXeDB9LSLHiG?p=preview

**Comment by kghaghada** [comment]
Interesting, the TimeAgo pipe does indeed pickup the change of locale with the moment script included in packages (through moment.locale('...') however the DataFormat pipe does not, only when reset is clicked does the displayed date change.

**Comment by mariolenis** [comment]
Pipes works differrent in angular 2, check the official guide [https://angular.io/docs/ts/latest/guide/pipes.html](url), you will find that pure pipes only are executed when it detects a truly change (value and type)

**Comment by kghaghada** [comment]
OK, I see the DateFormat and DateDifference pipes were changed to pure in [Removed impure flags from pure Pipes](https://github.com/urish/angular2-moment/commit/87bc1497ebd835b1dfe854c9037981b7c76a9b53) which is why I am seeing a difference in behaviour.
There isn't an issue linked to the change so I can't see the reason the change was made but I assume it was for performance reasons.
I'll see if I can find a workaround.

Thanks for your help

**Comment by urish** [comment]
@kghaghada my bad, for some reason I omitted this from the changelog. Added now: https://github.com/urish/angular2-moment/commit/eb60960509ec77e3221d1f36ae4ceb8641aa006e

and this is the relevant issue: #73
