### ISSUE TITLE
Not importing correctly - pipe not found

### ISSUE THREAD

**Issue by timmyg** [urish/angular2-moment#98]
Installed this package, imported into my main @NgModule like below, and placed it in my imports under that, but still get the error at the bottom.

```
import { MomentModule } from 'angular2-moment';
```

```
zone.js?fad3:355 Unhandled Promise rejection: Template parse errors:
The pipe 'amDuration' could not be found ("
          <tr>
            <td>Service</td>
            <td>[ERROR ->]{{ 365 | amDuration:'seconds' }}</td>
```

Have an angular 2 project using webpack that is similar in structure to https://github.com/AngularClass/angular2-webpack-starter

Any thoughts? Should this work when not using system.js?

**Comment by urish** [comment]
Definitely should work with System.js.

Did you add `MomentModule` to your own `NgModule` imports section?

**Comment by timmyg** [comment]
I did. I am not using system.js though.

**Comment by timmyg** [comment]
You can see exactly what ive done here:
https://github.com/crdschurch/crds-signin-checkin/compare/feature/US3508-view-list-of-service-events...moment

**Comment by urish** [comment]
@timmyg the link above says "There isn’t anything to compare."

There is an example with System.js:

http://plnkr.co/edit/ziBJ0mftSjnz0SrYPwbo?p=preview

**Comment by timmyg** [comment]
@urish it seems as though it was importing correctly - the pipe I was trying just wasnt working (amCalendar) but amDateFormat does seem to work.

**Comment by AKApumkin** [comment]
I have the same issue, but for the angular CLI JSON config file. there is a lot of conflicting information on where to put external libraries. Some say the in Scripts tag, some say inside packages and some say after packages. I have tried all, but no joy. below is half the config file, any nudge in the right direction would be appreciated. 

```
>   "addons": [],
  "packages": [
  ],
  "e2e": {
    "protractor": {
      "config": "./protractor.conf.js"
    }
  },
  "test": {
    "karma": {
      "config": "./karma.conf.js"
    }
  },
  "defaults": {
    "styleExt": "css",
    "prefixInterfaces": false
  },
  "angular2-moment": {
      "main": "./node_modules/angular2-moment/index.js",
      "defaultExtension": "js"
  }
```

**Comment by urish** [comment]
@AKApumkin in my projects, I didn't need to add anything to the CLI config json - it should work out of the box.

**Comment by darrendlin** [comment]
I'm having the same issue - except none of the pipes work for me.

I have the following line in my feature module
`import { MomentModule } from "angular2-moment/moment.module";`. It is also included in `@NgModule imports`.

I have tried `import { MomentModule } from "angular2-moment";` as well, with no luck.

This is the error I get `The pipe 'amFromUnix' could not be found` on this line `{{ 1456263980 | amFromUnix }}`

Any help is appreciated. Thanks.
