### ISSUE TITLE
amCalendar now support some more options

### ISSUE THREAD

**Issue by ykoehler** [urish/angular2-moment#99]
I would like to be able to do

 {{ date | amCalendar:{sameDay: '', nextDay: '', ... } }}

From momentjs docs: http://momentjs.com/docs/

From 2.10.5 moment supports specifying calendar output formats per invocation:

moment().calendar(null, {
    sameDay: '[Today]',
    nextDay: '[Tomorrow]',
    nextWeek: 'dddd',
    lastDay: '[Yesterday]',
    lastWeek: '[Last] dddd',
    sameElse: 'DD/MM/YYYY'
});
sameElse is used as the format when the moment is more than a week away from the referenceTime

**Comment by urish** [comment]
Seems like #64 should address that
